permalink: posts/:title 
exclude: ["readme.md", "CNAME"]
lsi: false
safe: true
incremental: false
highlighter: rouge
url: https://rxtx.wtf
enforce_ssl: rxtx.wtf
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
